databases:
  - name: django_url_shortener
    databaseName: django_url_shortener
    user: richkevan

services:
  - type: web
    name: url_shortener
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn admin.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oauth_api_demo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4