# Generated by Django 4.2.6 on 2023-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('long_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
